version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:1234@mysql:3306/perfectimages
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=perfectimages
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
